kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: openvpn
spec:
  scaleTargetRef:
    # point the HPA at the sample application
    # you created above
    apiVersion: apps/v1
    kind: Deployment
    name: erstwhile-panda-openvpn
  # autoscale between 1 and 10 replicas
  minReplicas: 1
  maxReplicas: 10
  metrics:
  # use a "Pods" metric, which takes the average of the
  # given metric across all pods controlled by the autoscaling target
  - type: Pods
    pods:
      metricName: openvpn_openvpn_server_connected_clients
      # target 500 milli-requests per second,
      # which is 1 request every two seconds
      targetAverageValue: 3