apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openvpn
  namespace: default
spec:
  endpoints:
  - interval: 15s
    port: metrics
  selector:
    matchLabels:
      app: openvpn
